### ISSUE TITLE
Würfel Event

### ISSUE THREAD

**Issue by roldka** [se-ii-mankomania/mankomania-app#5]
implementieren lt. Fimga https://www.figma.com/file/UksLrXVu5jXkC9B6n2BlE5/SE2-Mankomania?type=design&node-id=0-1&mode=design&t=qIUzVDqMTVnbNfm9-0

**Comment by laulaobm** [comment]
Verschoben auf Sprint 2. Vorläufige Version in Sprint 1 mit #11
